In [179]:
import numpy as np
import random

In [180]:
m = 100
X = 2 * np.random.rand(100, 1)
y = 4 + 3 * X + np.random.randn(100, 1)
X_b = np.c_[np.ones((100,1)),X]

try mini bach Size to 20

In [181]:
n_epochs = 50
mini_Size=20
t0, t1 = 5, 50 # learning schedule hyperparameters
def learning_schedule(t):
    return t0 / (t + t1)
theta = np.random.randn(2,1) # random initialization
t=0
for epoch in range(n_epochs):
   for i in range(0,m,mini_Size):
      t+=1
      random_index = np.random.randint(m)
      xi = X_b[random_index:random_index+mini_Size]
      yi = y[random_index:random_index+mini_Size]
      gradients = 2 * xi.T.dot(xi.dot(theta) - yi)
      eta = learning_schedule(t)
      theta = theta - eta * gradients

In [182]:
theta

array([[ 6.67835808e+49],
       [-6.13189161e+49]])

try mini bach Size to 5

In [183]:
n_epochs = 50
mini_Size=5
t0, t1 = 5, 50 # learning schedule hyperparameters
def learning_schedule(t):
    return t0 / (t + t1)
theta = np.random.randn(2,1) # random initialization
t=0
for epoch in range(n_epochs):
   for i in range(0,m,mini_Size):
      t+=1
      random_index = np.random.randint(m)
      xi = X_b[random_index:random_index+mini_Size]
      yi = y[random_index:random_index+mini_Size]
      gradients = 2 * xi.T.dot(xi.dot(theta) - yi)
      eta = learning_schedule(t)
      theta = theta - eta * gradients

In [184]:
theta

array([[3.63227187],
       [3.22273169]])

try mini bach Size to 70

In [185]:
n_epochs = 50
mini_Size=70
t0, t1 = 5, 50 # learning schedule hyperparameters
def learning_schedule(t):
    return t0 / (t + t1)
theta = np.random.randn(2,1) # random initialization
t=0
for epoch in range(n_epochs):
   for i in range(0,m,mini_Size):
      t+=1
      random_index = np.random.randint(m)
      xi = X_b[random_index:random_index+mini_Size]
      yi = y[random_index:random_index+mini_Size]
      gradients = 2 * xi.T.dot(xi.dot(theta) - yi)
      eta = learning_schedule(t)
      theta = theta - eta * gradients

In [186]:
theta

array([[-3.92934773e+80],
       [-4.64455688e+80]])

try mini bach Size to 100

In [187]:
n_epochs = 50
mini_Size=100
t0, t1 = 5, 50 # learning schedule hyperparameters
def learning_schedule(t):
    return t0 / (t + t1)
theta = np.random.randn(2,1) # random initialization
t=0
for epoch in range(n_epochs):
   for i in range(0,m,mini_Size):
      t+=1
      random_index = np.random.randint(m)
      xi = X_b[random_index:random_index+mini_Size]
      yi = y[random_index:random_index+mini_Size]
      gradients = 2 * xi.T.dot(xi.dot(theta) - yi)
      eta = learning_schedule(t)
      theta = theta - eta * gradients

In [188]:
theta

array([[-1.84568734e+42],
       [-1.89357653e+42]])

try mini bach Size to 80

In [189]:
n_epochs = 50
mini_Size=80
t0, t1 = 5, 50 # learning schedule hyperparameters
def learning_schedule(t):
    return t0 / (t + t1)
theta = np.random.randn(2,1) # random initialization
t=0
for epoch in range(n_epochs):
   for i in range(0,m,mini_Size):
      t+=1
      random_index = np.random.randint(m)
      xi = X_b[random_index:random_index+mini_Size]
      yi = y[random_index:random_index+mini_Size]
      gradients = 2 * xi.T.dot(xi.dot(theta) - yi)
      eta = learning_schedule(t)
      theta = theta - eta * gradients

In [190]:
theta

array([[5.37167663e+85],
       [5.99408371e+85]])