In [19]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session


/kaggle/input/demodata/demodata (1).csv


In [20]:

# Reading and writing CSV files with NumPy
# import genfromtxt function
from numpy import genfromtxt
# Read comma separated file
product_data = genfromtxt('/kaggle/input/demodata/demodata (1).csv', delimiter='\t')
# display initial 5 records
print(product_data)
# import numpy
import numpy as np
# Create a sample array
sample_array = np.asarray([ [1,2,3], [4,5,6], [7,8,9] ])
# Write sample array to CSV file
np.savetxt("my_first_demo.csv", sample_array, delimiter=",")

[[14. 32. 33.]
 [24. 45. 26.]
 [27. 38. 39.]]


In [21]:

# import pandas
import pandas as pd
# Read CSV file
sample_df=pd.read_csv('/kaggle/input/demodata/demodata (1).csv', sep='\t' , header=None)
# display initial 5 records
sample_df.head()
# Save DataFrame to CSV file
sample_df.to_csv('demo_sample_df.csv')